### ISSUE TITLE
Opencore 0.6.4 - macrecovery.py issue

### ISSUE THREAD

**Issue by harris1111** [acidanthera/bugtracker#1371]
im using opencore 0.6.4 and making installer in Windows 10, but i ran into this problem
![image](https://user-images.githubusercontent.com/52365112/102302562-dadf3f80-3f8b-11eb-9867-d475d0b4004d.png)
Im using python 3.9.1.

**Comment by logasans** [comment]
same here but i'm using clear linux
`Traceback (most recent call last):
  File "./macrecovery.py", line 425, in <module>
    sys.exit(main())
  File "./macrecovery.py", line 414, in main
    return action_download(args)
  File "./macrecovery.py", line 197, in action_download
    info    = get_image_info(session, bid=args.board_id, mlb=args.mlb,
  File "./macrecovery.py", line 120, in get_image_info
    headers, output = run_query(url, headers, post)
  File "./macrecovery.py", line 58, in run_query
    response = urlopen(req)
  File "/usr/lib/python3.8/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.8/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/usr/lib/python3.8/urllib/request.py", line 640, in http_response
    response = self.parent.error(
  File "/usr/lib/python3.8/urllib/request.py", line 569, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.8/urllib/request.py", line 502, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.8/urllib/request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 417: Expectation Failed
`

**Comment by harris1111** [comment]
> same here but i'm using clear linux
> `Traceback (most recent call last): File "./macrecovery.py", line 425, in <module> sys.exit(main()) File "./macrecovery.py", line 414, in main return action_download(args) File "./macrecovery.py", line 197, in action_download info = get_image_info(session, bid=args.board_id, mlb=args.mlb, File "./macrecovery.py", line 120, in get_image_info headers, output = run_query(url, headers, post) File "./macrecovery.py", line 58, in run_query response = urlopen(req) File "/usr/lib/python3.8/urllib/request.py", line 222, in urlopen return opener.open(url, data, timeout) File "/usr/lib/python3.8/urllib/request.py", line 531, in open response = meth(req, response) File "/usr/lib/python3.8/urllib/request.py", line 640, in http_response response = self.parent.error( File "/usr/lib/python3.8/urllib/request.py", line 569, in error return self._call_chain(*args) File "/usr/lib/python3.8/urllib/request.py", line 502, in _call_chain result = func(*args) File "/usr/lib/python3.8/urllib/request.py", line 649, in http_error_default raise HTTPError(req.full_url, code, msg, hdrs, fp) urllib.error.HTTPError: HTTP Error 417: Expectation Failed `

maybe recovery.py has issue somewhere.

**Comment by nkontopoul** [comment]
Same here on windows 10

\macrecovery>python macrecovery.py -b Mac-E43C1C25D4880AD6 -m 00000000000000000 download
Traceback (most recent call last):
  File "macrecovery.py", line 425, in <module>
    sys.exit(main())
  File "macrecovery.py", line 414, in main
    return action_download(args)
  File "macrecovery.py", line 198, in action_download
    diag=args.diagnostics, os_type=args.os_type)
  File "macrecovery.py", line 120, in get_image_info
    headers, output = run_query(url, headers, post)
  File "macrecovery.py", line 58, in run_query
    response = urlopen(req)
  File "C:\Users\hp\AppData\Local\Programs\Python\Python36\lib\urllib\request.py", line 223, in urlopen
    return opener.open(url, data, timeout)
  File "C:\Users\hp\AppData\Local\Programs\Python\Python36\lib\urllib\request.py", line 532, in open
    response = meth(req, response)
  File "C:\Users\hp\AppData\Local\Programs\Python\Python36\lib\urllib\request.py", line 642, in http_response
    'http', request, response, code, msg, hdrs)
  File "C:\Users\hp\AppData\Local\Programs\Python\Python36\lib\urllib\request.py", line 570, in error
    return self._call_chain(*args)
  File "C:\Users\hp\AppData\Local\Programs\Python\Python36\lib\urllib\request.py", line 504, in _call_chain
    result = func(*args)
  File "C:\Users\hp\AppData\Local\Programs\Python\Python36\lib\urllib\request.py", line 650, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 417: Expectation Failed

**Comment by Litarvan** [comment]
Same issue on Linux:

![Screenshot](https://cdn.discordapp.com/attachments/447725868140331019/788741244103688192/unknown.png)

**Comment by vit9696** [comment]
Are you sure these are not the servers being down? Do real Macs connect to internet recovery without issues?

**Comment by shajek** [comment]
same here, Expectation Failed

**Comment by harris1111** [comment]
> Are you sure these are not the servers being down? Do real Macs connect to internet recovery without issues?

yes, Im using 1 real macs and 1 pc with dualboot win/linux, Internet is normally, but I cant execute Macrecovery.py, same issue on 3 OS (python 3.9.1)

**Comment by harris1111** [comment]
![Screen Shot 2020-12-16 at 21 20 12](https://user-images.githubusercontent.com/52365112/102360359-7ef4d500-3fe4-11eb-9b3e-335e4457dd0d.png)
running in MacOS

**Comment by vit9696** [comment]
Sorry, but perhaps I was unclear. Real macs can connect to Apple servers via CMD+OPT+R (https://www.idownloadblog.com/2016/02/25/how-to-start-up-your-mac-in-internet-recovery-mode/). I wanted to know whether the real Macs can download it via an alternative implementation, because the error you face says that the server is unable to handle the request.

**Comment by harris1111** [comment]
ah okay I will try

**Comment by harris1111** [comment]
> Sorry, but perhaps I was unclear. Real macs can connect to Apple servers via CMD+OPT+R (https://www.idownloadblog.com/2016/02/25/how-to-start-up-your-mac-in-internet-recovery-mode/). I wanted to know whether the real Macs can download it via an alternative implementation, because the error you face says that the server is unable to handle the request.

Sorry i cant attach photos because I dont have devices to shoot, but I can connect it via CMD + OPT + R, I think Macrecovery.py has bug or something like that on source code, because my friends also face the problem like that ( tried python 2.7.18 to 3.9.1 )

**Comment by vit9696** [comment]
Do I understand you correctly that on a normal Mac you see the visual confirmation that internet recovery is starting (with an Earth logo, this is important) and then it starts correctly and lets you reinstall macOS and so on?

Just to give you an idea, it should look like this:

<img width="213" alt="Снимок экрана 2020-12-16 в 17 59 16" src="https://user-images.githubusercontent.com/4348897/102365276-6bd40c00-3fc8-11eb-8c57-de9c7ec33b1b.png">

**Comment by harris1111** [comment]
![image](https://user-images.githubusercontent.com/52365112/102367668-99cb4780-3fec-11eb-847e-80d98ae11b3b.png)
is that what you told me to do ? Sorry I never boot to internet recovery :(

**Comment by DooMFeaR** [comment]
Got the same error running the cmd with admin rights on Windows 10 x64.

`python macrecovery.py -b Mac-00BE6ED71E35EB86 -m 00000000000000000 download
Traceback (most recent call last):
  File "C:\Users\Teo\Desktop\OpenCore-0.6.4-RELEASE\Utilities\macrecovery\macrecovery.py", line 425, in <module>
    sys.exit(main())
  File "C:\Users\Teo\Desktop\OpenCore-0.6.4-RELEASE\Utilities\macrecovery\macrecovery.py", line 414, in main
    return action_download(args)
  File "C:\Users\Teo\Desktop\OpenCore-0.6.4-RELEASE\Utilities\macrecovery\macrecovery.py", line 197, in action_download
    info    = get_image_info(session, bid=args.board_id, mlb=args.mlb,
  File "C:\Users\Teo\Desktop\OpenCore-0.6.4-RELEASE\Utilities\macrecovery\macrecovery.py", line 120, in get_image_info
    headers, output = run_query(url, headers, post)
  File "C:\Users\Teo\Desktop\OpenCore-0.6.4-RELEASE\Utilities\macrecovery\macrecovery.py", line 58, in run_query
    response = urlopen(req)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.496.0_x64__qbz5n2kfra8p0\lib\urllib\request.py", line 214, in urlopen
    return opener.open(url, data, timeout)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.496.0_x64__qbz5n2kfra8p0\lib\urllib\request.py", line 523, in open
    response = meth(req, response)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.496.0_x64__qbz5n2kfra8p0\lib\urllib\request.py", line 632, in http_response
    response = self.parent.error(
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.496.0_x64__qbz5n2kfra8p0\lib\urllib\request.py", line 561, in error
    return self._call_chain(*args)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.496.0_x64__qbz5n2kfra8p0\lib\urllib\request.py", line 494, in _call_chain
    result = func(*args)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.496.0_x64__qbz5n2kfra8p0\lib\urllib\request.py", line 641, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 417: Expectation Failed`

**Comment by vit9696** [comment]
Use master version.
